# Generated by Django 4.2.1 on 2023-05-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShopModel',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_genre', models.CharField(choices=[('thriller', 'thriller'), ('fiction', 'fiction'), ('poem', 'poem'), ('religious', 'religious'), ('academic', 'academic')], max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
