# Generated by Django 4.2.1 on 2023-06-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_friend_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='me',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passport_No', models.IntegerField(unique=True)),
                ('page', models.CharField(choices=[('48', '48'), ('64', '64')], default='Choose', max_length=5)),
                ('validity', models.CharField(choices=[('5', '5'), ('10', '10')], default='Choose', max_length=5)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='first_app.users')),
            ],
        ),
    ]
