# Generated by Django 4.2.1 on 2023-06-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_users_alter_me_options_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Batch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(to='first_app.student'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='page',
            field=models.CharField(choices=[('48', '48'), ('64', '64')], default='48', max_length=5),
        ),
        migrations.AlterField(
            model_name='passport',
            name='validity',
            field=models.CharField(choices=[('5', '5'), ('10', '10')], default='5', max_length=5),
        ),
    ]
